- hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      command: docker pull gitikapinjani19/scientific-calculator:latest

    - name: Run the container
      command: docker run -d --name scientific-calculator gitikapinjani19/scientific-calculator:latest
