- hosts: localhost
  become: true
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image
      docker_image:
        name: gitikapinjani19/scientific-calculator
        source: pull

    - name: Run Calculator Container
      docker_container:
        name: scientific-calculator
        image: gitikapinjani19/scientific-calculator:latest
        state: started
        restart_policy: always
